name: ci-golang-workflow
on: 
    pull_request:
        branches: 
            - develop
jobs:
    check-application:
        runs-on: ubuntu-latest
        # strategy:
        #     matrix:
        #         go: ['1.14', '1.15']
        steps:
            - uses: actions/checkout@v2 # checkout the repository to the runner machine
            - uses: actions/setup-go@v2 # setup go environment
              with:
                #   go-version: ${{ matrix.go }}`
                    go-version: '1.15'
            - run: go test
            - run: go run math.go

            - name: Set up QEMU # description of the step
              uses: docker/setup-qemu-action@v3 # docker action to setup qemu

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: masilvadocker/fc2.0-ci-go:latest
